#!/usr/bin/env python3
"""
WAV to C array converter for TXW81x printer voice data.

Converts 16-bit PCM mono WAV files to C const arrays suitable for
embedding in firmware flash. Strips the 44-byte WAV header.

Usage:
  # Single file:
  python wav_to_c.py input.wav voice_sketch_pen

  # Batch mode (generate complete voice_data.c):
  python wav_to_c.py \
      --batch \
      sketch_pen.wav:voice_sketch_pen \
      line_art.wav:voice_line_art \
      pencil.wav:voice_pencil \
      anime.wav:voice_anime \
      cartoon.wav:voice_cartoon \
      ink_wash.wav:voice_ink_wash \
      --output project/printer/voice_data.c
"""

import sys
import os
import struct
import argparse


WAV_HEADER_SIZE = 44
BYTES_PER_LINE = 16  # hex values per line in output


def parse_wav_header(data):
    """Parse WAV header and return format info. Returns dict or raises ValueError."""
    if len(data) < WAV_HEADER_SIZE:
        raise ValueError("File too small for WAV header")

    riff = data[0:4]
    wave = data[8:12]
    if riff != b'RIFF' or wave != b'WAVE':
        raise ValueError("Not a WAV file (missing RIFF/WAVE magic)")

    fmt_tag = struct.unpack_from('<H', data, 20)[0]
    channels = struct.unpack_from('<H', data, 22)[0]
    sample_rate = struct.unpack_from('<I', data, 24)[0]
    bits_per_sample = struct.unpack_from('<H', data, 34)[0]
    data_size = struct.unpack_from('<I', data, 40)[0]

    return {
        'fmt_tag': fmt_tag,
        'channels': channels,
        'sample_rate': sample_rate,
        'bits_per_sample': bits_per_sample,
        'data_size': data_size,
    }


def validate_wav(info, filepath):
    """Validate WAV format matches expected specs."""
    if info['fmt_tag'] != 1:
        print(f"WARNING: {filepath} is not PCM (fmt_tag={info['fmt_tag']})")
    if info['channels'] != 1:
        print(f"WARNING: {filepath} is not mono (channels={info['channels']})")
    if info['bits_per_sample'] != 16:
        print(f"WARNING: {filepath} is not 16-bit (bits={info['bits_per_sample']})")
    if info['sample_rate'] != 8000:
        print(f"WARNING: {filepath} is not 8kHz (rate={info['sample_rate']})")


def pcm_to_c_array(pcm_data, var_name):
    """Convert raw PCM bytes to C source code string."""
    lines = []
    lines.append(f'const uint8_t {var_name}[] = {{')

    for i in range(0, len(pcm_data), BYTES_PER_LINE):
        chunk = pcm_data[i:i + BYTES_PER_LINE]
        hex_vals = ', '.join(f'0x{b:02X}' for b in chunk)
        lines.append(f'    {hex_vals},')

    lines.append('};')
    lines.append(f'const uint32_t {var_name}_len = {len(pcm_data)};')
    return '\n'.join(lines)


def convert_single(wav_path, var_name, output_path=None):
    """Convert a single WAV file to C array."""
    with open(wav_path, 'rb') as f:
        raw = f.read()

    info = parse_wav_header(raw)
    validate_wav(info, wav_path)
    print(f"  {wav_path}: {info['sample_rate']}Hz, {info['channels']}ch, "
          f"{info['bits_per_sample']}bit, {info['data_size']} bytes")

    pcm_data = raw[WAV_HEADER_SIZE:]
    c_code = pcm_to_c_array(pcm_data, var_name)

    if output_path:
        with open(output_path, 'w', encoding='utf-8') as f:
            f.write(c_code + '\n')
        print(f"  Written to {output_path}")
    else:
        print(c_code)

    return pcm_data


def batch_convert(pairs, output_path):
    """Convert multiple WAV files into a single voice_data.c."""
    parts = []
    parts.append('/* Auto-generated by wav_to_c.py -- do not edit manually */')
    parts.append('#include "voice_data.h"')
    parts.append('')

    for wav_path, var_name in pairs:
        with open(wav_path, 'rb') as f:
            raw = f.read()

        info = parse_wav_header(raw)
        validate_wav(info, wav_path)
        print(f"  {wav_path}: {info['sample_rate']}Hz, {info['channels']}ch, "
              f"{info['bits_per_sample']}bit, {info['data_size']} bytes")

        pcm_data = raw[WAV_HEADER_SIZE:]
        c_code = pcm_to_c_array(pcm_data, var_name)
        parts.append(c_code)
        parts.append('')

    content = '\n'.join(parts)
    with open(output_path, 'w', encoding='utf-8') as f:
        f.write(content)
    print(f"  Written {len(pairs)} clips to {output_path}")


def main():
    parser = argparse.ArgumentParser(
        description='Convert WAV files to C arrays for TXW81x printer voice')
    parser.add_argument('wav_file', nargs='?', help='Input WAV file (single mode)')
    parser.add_argument('var_name', nargs='?', help='C variable name (single mode)')
    parser.add_argument('--batch', nargs='+',
                        help='Batch: wav_path:var_name pairs')
    parser.add_argument('--output', '-o', help='Output file path')
    args = parser.parse_args()

    if args.batch:
        pairs = []
        for item in args.batch:
            if ':' not in item:
                print(f"ERROR: batch item '{item}' must be wav_path:var_name")
                sys.exit(1)
            wav_path, var_name = item.split(':', 1)
            pairs.append((wav_path, var_name))
        output = args.output or 'voice_data.c'
        batch_convert(pairs, output)
    elif args.wav_file and args.var_name:
        convert_single(args.wav_file, args.var_name, args.output)
    else:
        parser.print_help()
        sys.exit(1)


if __name__ == '__main__':
    main()
